### ISSUE TITLE
Add dropdown-group directive

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-panels#17]
> When you say dropdown-group, do you essentially mean bootstrap accordions

Yeh basically. Just a way to orchestrate the style of a group of dropdowns with a default style and adding a bottom/top margin for the group. So rather than:

```rst
.. dropdown:: My Content
    :container: mt-3 shadow
    :title: bg-primary text-white text-center font-weight-bold
    :body: bg-light text-right font-italic

    Is formatted

.. dropdown:: My Content
    :container: shadow
    :title: bg-primary text-white text-center font-weight-bold
    :body: bg-light text-right font-italic

    Is formatted

.. dropdown:: My Content
    :container: mb-3 shadow
    :title: bg-primary text-white text-center font-weight-bold
    :body: bg-light text-right font-italic

    Is formatted
```

You could have:

```rst
.. dropdown-group::
    :container: shadow
    :title: bg-primary text-white text-center font-weight-bold
    :body: bg-light text-right font-italic

    .. dropdown:: My Content
    
        if formatted

    .. dropdown:: My Content
    
        if formatted

    .. dropdown:: My Content
    
        if formatted
```

_Originally posted by @chrisjsewell in https://github.com/executablebooks/sphinx-panels/pull/15#issuecomment-629560076_

**Comment by chrisjsewell** [comment]
This example from google search is actually quite a nice example; with the rounded edges in the corners:

![image](https://user-images.githubusercontent.com/2997570/82171946-a5248c00-98c0-11ea-978e-06aaad7120ce.png)

(just re-watched this film, is flippin great 😂 )

**Comment by chrisjsewell** [comment]
This works quite well:

```css
.dropdown-group .dropdown .summary-title {
    border-bottom: 0 !important;
    font-weight:700 !important;
}
.dropdown-group .dropdown:not(:last-child) {
    margin-bottom: 0 !important;
    border-radius: 0 !important;
}
.dropdown-group .dropdown:first-child,
.dropdown-group .dropdown:first-child .summary-title {
    border-radius: 1rem 1rem 0rem 0rem !important;
}
.dropdown-group .dropdown:last-child,
.dropdown-group .dropdown:last-child .summary-title {
    border-radius: 0rem 0rem 1rem 1rem !important;
}

.dropdown-group .dropdown:last-child {
    margin-bottom: 24px !important;
}
```
